### ISSUE TITLE
i<CR><ESC>

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#107]
There's something strange, at least `i<CR><CR><ESC>` works.
See also https://github.com/aligrudi/neatvi/issues/86

**Comment by kyx0r** [comment]
Fixed now, Thanks!

**Comment by polluks** [comment]
`r` is fixed, but `f<SPC>i<CR><ESC>` fails.

**Comment by kyx0r** [comment]
How does it fail?

**Comment by polluks** [comment]
It seems the escape cancels the insert and it looks like before. Non-space splits are fine.

**Comment by polluks** [comment]
thanks
