### ISSUE TITLE
Get current filename with %

### ISSUE THREAD

**Issue by Vouivre** [kyx0r/nextvi#11]
I very often execute a command on the file in the current buffer with

    :! cmd %

where `cmd` is my command. It worked fine until commit `ced7ccd` and it seems since commit `d11fbae` % is not replaced anymore with the filename in the current buffer. Perhaps there is something wrong the [following function](https://github.com/kyx0r/nextvi/blob/master/ex.c#L158).

Or is it stored in another variable now ?

**Comment by Vouivre** [comment]
If you have an idea, just let me know. For the moment I need `%` only to compile some files. But I have always a `Makefile` so I could execute 

    :! make

until a solution is found..... if a solution is needed!

I'll also think about it. Thank you!

**Comment by kyx0r** [comment]
Now i've given it some thought. diff last commit.

Is the issue solved?

**Comment by Vouivre** [comment]
Amazing!!
