### ISSUE TITLE
new filetype for linenumbers (or reuse /#)

### ISSUE THREAD

**Issue by devank4000** [kyx0r/nextvi#116]
adding a different filetype for linenumbers would make customizing colors much easier
besides there already exists a filetype for ^v so it could also include line numbers

**Comment by kyx0r** [comment]
Indeed. However, nothing is finalized yet, I'm still cooking. It will probably come in last. There are quite a few problems to resolve still.

**Comment by kyx0r** [comment]
https://github.com/kyx0r/nextvi/commit/1b89607b2655b98920a8d703d2d8ada9a89f5e2c

I think it's ready. Scouting for what else can be improved in the editor in the meantime
