### ISSUE TITLE
misaligned prompt when both relative line numbers and status are enabled

### ISSUE THREAD

**Issue by devank4000** [kyx0r/nextvi#118]
when relative line numbers are enabled with 8# along with permanent status line, the prompt is rendered 3 characters from the left end of the window
![image](https://github.com/user-attachments/assets/fff86312-4246-47fc-8467-4c49cee1d933)

**Comment by kyx0r** [comment]
Fixed

**Comment by devank4000** [comment]
thanks! prompt now works as expected
