### ISSUE TITLE
[Question] 23. like for d and y 

### ISSUE THREAD

**Issue by dostoievsky** [kyx0r/nextvi#120]
> 28. Added ability to view the numbers for arguments that keys e,w,E,W,b,B
may take. keybind: ^v Pressing again will change the key mode, specifying
any vi_arg1 will exit the mode. This is a major step up to how navigation
works in vi, it makes it so much easier to use because now you can see where
you are going. These special numbers and their colors can be customized
through conf.c. As of the latest git version, the feature will work correctly
even if there is bidi text, double width characters and text reordering.

It is possible I use that for d or y?
like I know i can do something like d10l or y10l

and that will yank/cut 10 chars from the cursor, but I need to count how much chars I must to do that.

And maybe, there is a better way of doing that? 

thanks!

**Comment by kyx0r** [comment]
Well, currently ^v only gives you the word motions. You probably know things like d10e, but just in case.
Problem with l motion is that it would be pretty cluttered. But it can definitely be done. Imagine
1234567891123456789
Then you can put a syntax highlight rule on 11 to make the distinction.

**Comment by kyx0r** [comment]
1234567890123456789

Or 01, this is probably even better

**Comment by dostoievsky** [comment]
` You probably know things like d10e, but just in case.`

I guess that is what I wanted, and what I tried but I didnt get results. 

`Then you can put a syntax highlight rule on 11 to make the distinction.`

I do not see this syntax highlight working, I have archieved that one, but I didnt understand what I did. 

I thank you. I really apreciate this editor, and I've been using for my C studies and I hope I can soon adapt it to other langagues!
