### ISSUE TITLE
How do we switch batch and forth from 'visual' mode to 'ex' mode?

### ISSUE THREAD

**Issue by brunobord** [kyx0r/nextvi#122]
Hello,

I've recently discovered your vi clone because of a deep exploration of `ed(-like)` and `ex(-like)` editors and I'm having fun diving into this funny side of text editors.

Although, I know that when opening a file in 'ex' mode, you can switch to visual mode (the good'ol' 'vi') using the `':vi(sual)'` command.

But you can also go back from visual to ex mode using the `gQ` keystroke.

Unfortunately, I couldn't find how to do so in `nextvi`. Could you please either tell me what's the command to launch, or, if it doesn't exist, add it to `nextvi`?

**Comment by kyx0r** [comment]
Hi! Thanks for stopping by. You can switch using keybind ^o. It's also mentioned in 71.

**Comment by brunobord** [comment]
oookay so I missed it. Thanks for the quick response!

**Comment by kyx0r** [comment]
With the latest, now it is also possible from visual to ex mode using Posix compatible key Q.
