### ISSUE TITLE
[Question] Problens with identation/tabs

### ISSUE THREAD

**Issue by dostoievsky** [kyx0r/nextvi#123]
Hello!

I've been using `:se tbs=x` and also placed this as 4 by default in my EXINIT.
But things dosent seens to work correctly:
nextvi idents correctly, but when diffing, and sending things to git upstream, I can see that the identation is all messed up as in the following image:

![print](https://github.com/user-attachments/assets/7c3488d4-1fed-45e8-96df-febabdb30f65)

I endend giving up and formating the code on nvim, because it shows me the | tabs marks throught a plugin. 

I think I am doing something wrong, and I dont know what is. 
I also know about shift+v and it is a really nice feature, but I still think I am missing something on this subject. Can you give me some ideas? 

![print](https://github.com/user-attachments/assets/32e71d5e-c49e-48cb-a5e8-8012304b886d)

I think it has something about those --> marks, and I would like to know what they mean.

In nvim, and I think in others editors, tabs produces -- only, but in nextvi, tabs produces -->, this is something about the old war of tabs vs spaces? 

Also, it is possible to C^c to X clipboard like in (n)vim when we do set clipboard?

**Comment by kyx0r** [comment]
---> Is a tab character.
tbs option only tells how to render the tab character (that is it's width).

Nextvi is primarily designed to work with tabs as indentation. When mixing spaces and tabs you have to make conscious effort of where they are.

I rarely deal with spaces for indentation, but when I have no choice use feature 5. This way, you can do all your work using tabs and when you think it's done convert the file to spaces. Of course that's only true if you're not mixing them, otherwise you would need to modify the regex to replace the tabs in the way that suits your needs.

**Comment by kyx0r** [comment]
> Also, it is possible to C^c to X clipboard like in (n)vim when we do set clipboard?

In theory, yes. You could make a macro to yank some region and use :w \!xclip -selection clipboard

**Comment by kyx0r** [comment]
Please see this issue as well.
https://github.com/kyx0r/nextvi/issues/124

**Comment by dostoievsky** [comment]
Sorry for not being in touch, and again thanks for the answers on the subjects.
I am closing this issue, since my main question (about tabs and spaces) as provided, and I just added that extra question on the fly, but since there is another issue open about this, I will continue there if I had any question about the clip subject. 

As for a last question, that escape thoose topics, do you think packages are welcome for this project? I want to create a port for FreeBSD since there is none for nextvi in [freshports](https://www.freshports.org/search.php?query=nextvi&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive), but I dont know if that is wellcome for the caracterist of the application itself.

**Comment by dostoievsky** [comment]
Also, other question: is 8 tbs your default? or you place such a big ident to "force" user to change?

**Comment by kyx0r** [comment]
> Sorry for not being in touch, and again thanks for the answers on the subjects. I am closing this issue, since my main question (about tabs and spaces) as provided, and I just added that extra question on the fly, but since there is another issue open about this, I will continue there if I had any question about the clip subject.
> 
> As for a last question, that escape thoose topics, do you think packages are welcome for this project? I want to create a port for FreeBSD since there is none for nextvi in [freshports](https://www.freshports.org/search.php?query=nextvi&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive), but I dont know if that is wellcome for the caracterist of the application itself.

Packages are welcome, however it will be on you to update and maintain such package. Until I figure out / decide to make official tagged release. Most users make their packages to be a git clone and run the ./cbuild.sh or their own compile script.

> Also, other question: is 8 tbs your default? or you place such a big ident to "force" user to change?

Hahaha, thank you, you made my day.
"Tabs are 8 characters, and thus indentations are also 8 characters. There are heretic movements that try to make indentations 4 (or even 2!) characters deep, and that is akin to trying to define the value of PI to be 3."
[source](https://www.reddit.com/r/kernel/comments/enpwkj/tab_width_in_kernel_coding_style/#:~:text=Tabs%20are%208%20characters%2C%20and,of%20PI%20to%20be%203.)

In all seriousness, 8 is the standard on unix. If you don't believe me the run this and count the number of spaces prior to 'a':
```echo -e "\ta"```

**Comment by dostoievsky** [comment]
hahaha thanks for the reply! 
I never thought of ask myself if there was a (L)unix standart for that, and at $JOB people usually uses 4, and I have seen 2 for some projects and even 3 for some MS XMLS... But since I see alot of tbs as 4 I thought that was a universal standart.

Also in the reddit, that is a nice statement:

> The answer to that is that if you need more than 3 levels of indentation, you're screwed anyway, and should fix your program.
In short, 8-char indents make things easier to read, and have the added benefit of warning you when you're nesting your functions too deep. Heed that warning.

I'll try to start using it as 8 from now on.

**Comment by Un1q32** [comment]
The amount of indentation I use depends on the language, In C I use 2 spaces because clang-format uses 2 spaces, in shell I use 4 because I maintain pfetch and that has always used 4, and changing it would be a hassle, and making my editor use 4 space for pfetch and 2 space for everything else would be a pain.  In other languages I like to use whatever the most popular formatting tool uses.
