### ISSUE TITLE
sh syntax highlighting, when # is preceeded by certain characters it shouldn't count as a comment

### ISSUE THREAD

**Issue by Un1q32** [kyx0r/nextvi#125]
When # is preceded by certain characters, like `\` or `-`, it doesn't count as a comment.  A real world example is `curl` which has a `-#` option to show a simple progress bar when downloading things.  A command like `curl -o file.txt -# https://example.com/file.txt` is wrongly highlighted to show everything after the # as a comment, when there is actually no comment in that line

neovim correct highlighting:
![image](https://github.com/user-attachments/assets/17e3f813-5ab6-4b5a-89d3-673964454396)

nextvi incorrect highlighting:
![image](https://github.com/user-attachments/assets/fd517be5-74df-44c1-b15f-46edadf94b2b)

you can also see github's syntax highlighting is correct:
```sh
#!/bin/sh
# real comment
curl -o file.txt -# https://example.com/file.txt
```

**Comment by kyx0r** [comment]
Hi Joey,
Thank you for report, is it fixed now?

**Comment by Un1q32** [comment]
Actual comments aren't highlighted when at the start of a line now
![image](https://github.com/user-attachments/assets/a52f16af-52a1-4488-88b1-d550d1974fed)

**Comment by Un1q32** [comment]
Also it seems like any character being directly before the # makes it not count, this script will print a#b to the terminal
```sh
#!/bin/sh
func() {
  printf "%s\n" "$@"
}

func a#b
```

**Comment by Un1q32** [comment]
So a comment character must either be at the start of a line or preceded by whitespace I guess

**Comment by kyx0r** [comment]
try this:
```
        {"sh", "[ \t](#.*$)|^(#.*$)", {0, 2 | SYN_IT, 2 | SYN_IT}},
```

Let me know if this accounts for all edge cases or not

**Comment by kyx0r** [comment]
I've reverted the commit and pushed this version on master now

**Comment by Un1q32** [comment]
seems to work correctly now
