### ISSUE TITLE
[Issue] Node hot reloading when file change

### ISSUE THREAD

**Issue by dostoievsky** [kyx0r/nextvi#127]
I am doing something with react, it seens when I edit a file with nextvi, the development server seens unable to detect that the file changed and it wont make the hot reload feature. This works in nvim and others editors as well, and I keeps me minding why it dosent happens when editing the file with nextvi. Also, other editors, IDE's as well, are able to move changes to the editor buffer when I do some command that alters the file, but this dont happens with nextvi. 

Could you give me tips in what should I look for or learn to make this possible with this editor?

**Comment by kyx0r** [comment]
> I am doing something with react, it seens when I edit a file with nextvi, the development server seens unable to detect that the file changed and it wont make the hot reload feature. This works in nvim and others editors as well, and I keeps me minding why it dosent happens when editing the file with nextvi. 

Doesn't look like a nextvi problem to me. Does saving the file change the file, if so then it's development server problem.

>Also, other editors, IDE's as well, are able to move changes to the editor buffer when I do some command that alters the file, but this dont happens with nextvi.

To re-read the file, use :e!

Kind Regards,
Kyryl

**Comment by dostoievsky** [comment]
It seens that the problem it is not the editor and the development server, or maybe the development server + OS. In linux everything runs fine. 
Also thanks for :e!
