### ISSUE TITLE
Brackets and Parentheses Direction Reversed

### ISSUE THREAD

**Issue by unrealapex** [kyx0r/nextvi#145]
Bracket and and parenthesis keymaps move in reversed direction than how they are documented in the README. For example, <kbd>{</kbd> goes down instead of up.

     {             Move to next <{> section up
     }             Move to next <{> section down
     [             Move to next <Newline> section up
     ]             Move to next <Newline> section down

**Comment by unrealapex** [comment]
To clarify, the documentation was correct, the behavior of the keys was wrong. POSIX Vi and Vim both implement the keymaps in the way I have described.

**Comment by unrealapex** [comment]
I would strongly suggest changing the behavior to what is defined by POSIX, however, I acknowledge you are free to implement these binds in which whatever way you choose.

**Comment by kyx0r** [comment]
Thank you, the goal of Nextvi was never to be a 100% Posix compatible clone. I only take the good ideas from ex/vi and implement them in my vision. I don't typically deviate without a reason, but now if I change this back to POSIX it is going to mentally bother me considering how awkward it is to use.

If you still insist on posix behavior, you can remap any keybinds using this patch:
https://github.com/kyx0r/nextvi/blob/patches/kbd_layout.patch

This will probably be more future proof than modifying the conditions in switch.
