### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#147]
```
In file included from vi.c:37:
led.c: In function 'led_render':
led.c:219:36: warning: 'c' may be used uninitialized [-Wmaybe-uninitialized]
  219 |                                 if (i < c && stt[i] == p->off) {
      |                                    ^
led.c:150:16: note: 'c' was declared here
  150 |         int j, c, l, i, o, n = r->n;
      |                ^

**Comment by kyx0r** [comment]
I've seen this. I the compiler is wrong. It's only true if malloc fails, but if it does we abort.

**Comment by kyx0r** [comment]
I think I can prevent this by swapping the meaning between bound and c without having to introduce redundant initialization.

**Comment by kyx0r** [comment]
Nah, better leave be. It's fixed in the next gcc 14+ it seems. Though oddly I can get this warning to show only on one system and not the other despite having same gcc version
