### ISSUE TITLE
Is there a way to remember the last positon?

### ISSUE THREAD

**Issue by qianqiangliu** [kyx0r/nextvi#151]
I think it would be more convenient to remember the last editing position.

**Comment by kyx0r** [comment]
Yes, you can use ```[ ]``` marks. Or if you want a full going up and down the edit stack using this patch:
https://github.com/kyx0r/nextvi/blob/patches/undojump.patch

**Comment by qianqiangliu** [comment]
If I exit nextvi and open it again, will the last position be remembered?

**Comment by kyx0r** [comment]
No, that's not what I thought you meant. 
If you want to remember the position after closing, I recommend using the suspend functionality instead. keybind. <^Z>

If that's not sufficient you could make a macro to save and read the position on startup, lets say from a file in a /tmp directory. This can be done using EXINIT and basic shell scripting.
