### ISSUE TITLE
Darwin error

### ISSUE THREAD

**Issue by polluks2** [kyx0r/nextvi#19]
````sh
/usr/bin/cc vi.c -pedantic -Wall -Wextra -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wfatal-errors -std=c99 -D_POSIX_C_SOURCE=200809L -o vi
vi.c:2049:14: fatal error: use of undeclared identifier 'SIGWINCH'
                        sigaction(SIGWINCH, &sa, NULL))
                                  ^
1 error generated.
````
Darwin mbp 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
````c
#if  (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
#define SIGWINCH 28     /* window size changes */
#define SIGINFO 29      /* information request */
#endif
````

**Comment by kyx0r** [comment]
Just conditionally add -D_DARWIN_C_SOURCE in build.sh to CFLAGS. That should solve it. Can you check the output of uname command on darwin?

**Comment by kyx0r** [comment]
Interesting so see more strict header files, SIGWINCH is not in posix, but I still want to keep D_POSIX_C_SOURCE because it prevents use of gnu extensions. Maybe one day SIGWINCH becomes the standard so that i could just bump the version number...

**Comment by polluks** [comment]
Works, would you like to add it officially?
By the way MorphOS (I made a port) has
````c
#ifndef _POSIX_SOURCE
#define SIGIO   23      /* input/output possible signal */
#define SIGXCPU 24      /* exceeded CPU time limit */
#define SIGXFSZ 25      /* exceeded file size limit */
#define SIGVTALRM 26    /* virtual time alarm */
#define SIGPROF 27      /* profiling time alarm */
#define SIGWINCH 28     /* window size changes */
#define SIGINFO 29      /* information request */
#endif
````

**Comment by kyx0r** [comment]
Stefan ***@***.***> wrote:

> Works, would you like to add it officially?
> By the way MorphOS (I made a port) has

Hello Stefan, I would add this. But you
did not send any patch, if thats an issue let
me know the output of uname command on those
systems (since I have no idea) and I will
add the check into build script myself.

By the way, last 2 commits significantly improve
some previously annoying aspects of related
to file navigation, try it out some time.

Kind Regards,
Kyryl

**Comment by polluks** [comment]
Right now I'm doing an SDK update... stay tuned.
BTW 74 downloads so far https://aminet.net/package/text/edit/nextvi

**Comment by kyx0r** [comment]
Stefan ***@***.***> wrote:

> Right now I'm doing an SDK update... stay tuned.
> BTW 74 downloads so far https://aminet.net/package/text/edit/nextvi

That amiga repository looks very interesting, thanks for
introducing me to it.

**Comment by kyx0r** [comment]
> > Just conditionally add -D_DARWIN_C_SOURCE in build.sh to CFLAGS. That should solve it.
> 
> It works for me. Here is my package for nix https://github.com/sikmir/nur-packages/blob/master/pkgs/suckless/nextvi/default.nix
> 
> > Can you check the output of uname command on darwin?
> 
> `Darwin`

Hello, I've added the Darwin condition. Hopefully
it's right. The string matches case sensitive so I assume
there is no variation and "Darwin" is consistent.

Thank you.
