### ISSUE TITLE
why not use a Makefile rather than a build.sh?

### ISSUE THREAD

**Issue by apprehensions** [kyx0r/nextvi#25]

**Comment by polluks** [comment]
because of its simplicity

**Comment by 173duprot** [comment]
Why do you need to incrementally build something that completes in 0.5 sec on a thinkpad.

**Comment by LinArcX** [comment]
I really like your approach.

Makefiles are extra dependencies. We have shell script and it's enough.

**Comment by LinArcX** [comment]
At the end of the day, makefiles will run user space commands from your shell. And execute your compiler. (With proper arguments)

Why you need to add that extra layer for just building a software.

You can directly talk to your shell.

This will brings us:

1. You (and everyone else that wants to read your project) don't need to learn makefiles syntax(IMO, one of the world)
2. It's easier to understand what's going on under the hood. (By removing extra layer of unnecessary dependency)

Ps: it's not a good argument that if project X, use technology Y, we should use it too.

Think about what I Said before. Is it reasonable for you?

**Comment by apprehensions** [comment]
using a 'shell script' that by your argument already does what the makefile does, you are simply re-inventing the wheel.

+ but muh contributions to makefile
makefile is a standard, and the same argument applies to build.sh, it requires someone to know shell script.

+ but muh readability and 'dependency'
like i said, make and sh are defined by POSIX. if a system doesnt have `make`, or isnt' able to get it. it is invalidating standards to keep shit together. plus, `make -n`. 

i don't see ANY reasoning why someone should re-invent the wheel especially when someone can just use a build system standard that all C programmers understand already.

**Comment by apprehensions** [comment]
No response?

**Comment by kyx0r** [comment]
Makefile has been added to patches branch. Basically that's where all the optional stuff goes anyways. For those who rely/need it.
