### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#27]
```
vi.c:2047:14: fatal error: use of undeclared identifier 'SIGWINCH'
                        sigaction(SIGWINCH, &sa, NULL))
                                  ^
```

**Comment by kyx0r** [comment]
Please check whether this condition actually works. Maybe not reliable.
https://github.com/kyx0r/nextvi/blob/master/build.sh#L13

If that does not help, remove -D_POSIX_C_SOURCE=200809L

SIGWINCH is not standard flag, but its too good to pass on though.

**Comment by OldWorldOrdr** [comment]
> Please check whether this condition actually works. Maybe not reliable. https://github.com/kyx0r/nextvi/blob/master/build.sh#L13
> 
> If that does not help, remove -D_POSIX_C_SOURCE=200809L
> 
> SIGWINCH is not standard flag, but its too good to pass on though.

it worked i can see it in the command line

**Comment by OldWorldOrdr** [comment]
> If that does not help, remove -D_POSIX_C_SOURCE=200809L

that worked

**Comment by OldWorldOrdr** [comment]
also thanks for the quick responce
