### ISSUE TITLE
zsh completion hangs

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#28]
Tab auto completion hangs in zsh, I've never read a zsh completion file before, but it looks like its running `vi --version` to figure out if it's vim or not.  Would probably be fixed by adding a `--version` page, or by exiting if not running interactively, since it seems to just fallback to only auto completing file paths if its not vim.

**Comment by kyx0r** [comment]
No idea why zsh would use vim for completion, or I am misunderstanding here. I've never used zsh, but already from the start this sends some red flags. Clearly, Nextvi is not responsible to account for bad design made in other programs.

**Comment by OldWorldOrdr** [comment]
zsh has completion for vim, and some distros link vi to vim, so they have a script that checks if vi is vim by running vi --version.  They expect that other vi implementations will either show a version page or exit with illegal option, instead of interpreting the argument as a file name.  The solution is just to make invoking with --version do something besides opening the editor (like showing a version number for example) or to exit if not running iteratively (which should be done anyway)

**Comment by julio-design** [comment]
Changing the binary name solves the problem. In the `build.sh` or the `Makefile` whatever you have, change the binary name and rebuild. May be is brut force but it works

**Comment by kyx0r** [comment]
This is should be resolved now.
