### ISSUE TITLE
`:set backspace=indent,eol,start` doesn't work in FreeBSD from TTY

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#29]
I was told [here](https://github.com/aligrudi/neatvi/issues/52#issuecomment-1274190047) that i could make backspace function like it does in vim.  How?

**Comment by OldWorldOrdr** [comment]
not sure why i didnt just try the command as is before makiung this :P  ig i assumed since it said "something similar" it would be different

**Comment by OldWorldOrdr** [comment]
wait it doesnt work on freebsd

**Comment by OldWorldOrdr** [comment]
wait it works on bsd from an ssh session what?

**Comment by OldWorldOrdr** [comment]
maybe its something to do with not being in an x session

**Comment by kyx0r** [comment]
Historically, there is a discrepancy between the keycode for backspace on linux and traditional unix systems. I won't remeber all exact details, but you may research it. If you want to be sure, try using ^h and perhaps that will work on your system.

Oh, and by the way, there is no options like that in nextvi, backspace just works by default.
