### ISSUE TITLE
Support for LSP? 

### ISSUE THREAD

**Issue by LinArcX** [kyx0r/nextvi#34]
Hi, 

I'm a long term neovim user and I want to switch to a More minimal alternative that I can read/understand it's code base and change it based on my needs. 

Untill I find nextvi.

I think the only thing that I will miss from neovim is code Intellisense via LSP.

Im not sure how you guys solved this issue in your daily programming.

I'm curious to know do you use extra tools like ctags? Or you don't use intelisence at all?

And what are yours reasons. Is it more efficient?

If I want to add Intellisense, where should I start? Or is it better to use external alternatives like ctags?

**Comment by kyx0r** [comment]
I use feature 8. No need for ctags and it is probably faster. If its not fast enough use threaded_search.patch.

https://github.com/kyx0r/nextvi/blob/patches/threaded_search.patch

**Comment by LinArcX** [comment]
thanks.

Now after some thought, I feel that I don't need LSP at all :)
