### ISSUE TITLE
About ^a

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#41]
How about also supporting "*" as key?

**Comment by kyx0r** [comment]
diff --git a/vi.c b/vi.c
index c70f1a0..8be8d5d 100644
--- a/vi.c
+++ b/vi.c
@@ -873,6 +873,7 @@ static int vi_motion(int *row, int *off)
 			return -1;
 		break;
 	case TK_CTL('a'):
+	case '*':
 		if (!(cs = vi_curword(xb, *row, *off, cnt)))
 			return -1;
 		ex_krsset(cs, +1);


If you just add this it will work; but the result won't be centered, need to add one more same line in vi();. Not sure if its interesting enough to use a key for duplicated behavior or a slightly different one. I don't think i'll be using it, but if you want make a patch and I'll add it to patches, it will get auto maintained by me. Thats how I handle user requests, then they can just chose what patch they want to use.

**Comment by polluks** [comment]
See #45
