### ISSUE TITLE
`clock_gettime` function in led.c isn't portable

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#53]
MacOS has only had `clock_gettime` since 10.12 sierra ~2016

**Comment by kyx0r** [comment]
As an alternative, you could use gettimeofday(), here is dilemma:
SVr4, 4.3BSD.  POSIX.1-2001 describes gettimeofday() but not
settimeofday().  POSIX.1-2008 marks gettimeofday() as obsolete,
recommending the use of [clock_gettime(2)](https://www.man7.org/linux/man-pages/man2/clock_gettime.2.html) instead.

Any ideas?

**Comment by kyx0r** [comment]
I moved the feature into patches, in my opinion its not worth the risk using gettimeofday() or going back to using time() which is only limited to a second accuracy and is influenced by clock fluctuations making it not so pleasant or consistent. 

gettimeofday() may not be present in the future.
