### ISSUE TITLE
segfault when trying to edit file that doesnt exist or is a directory

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#54]
![image](https://github.com/kyx0r/nextvi/assets/57970114/f346be21-07e4-4a6e-a31a-010316abea25)

**Comment by OldWorldOrdr** [comment]
the same issue happens if I don't use ccache

**Comment by kyx0r** [comment]
Sorry I broke that code again, hard to define all the requirements and edge cases. I don't know when it would make sense to error, problem is the error leaves unclean state which you can't go back and undo. I'll fix the crash but then something else won't work exactly how it needs to. Compromise somewhere in the middle.

**Comment by kyx0r** [comment]
Ok this should be fixed now for good. e! also should still work fine and not cause problems on read.
