### ISSUE TITLE
Issues with stdin_pipe

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#60]
if only - is specified, an additional empty buffer will be opened
if - and a file are specified, - will inherent the name of the last file

I tested if it was a result of the recent command line changes, since I saw similar issues when testing those, but checking out 6d98b263af195a05e43a4f05a60fe1a631f30554 and using 3 day old stdin_pipe patch had the same issue

![image](https://github.com/kyx0r/nextvi/assets/57970114/099446ba-934c-4ae3-855f-5b4d125758db)

**Comment by OldWorldOrdr** [comment]
when specifying multiple -

![image](https://github.com/kyx0r/nextvi/assets/57970114/a4eef587-70b6-444f-b8fc-228db11f2e1a)

**Comment by OldWorldOrdr** [comment]
if a filename is first, it behaves like - isn't there

https://github.com/kyx0r/nextvi/assets/57970114/75d95d6c-7c15-4d30-b35d-ab032118f7c5

**Comment by kyx0r** [comment]
Try the new version/

**Comment by OldWorldOrdr** [comment]
vim also doesn't open multiple files when one of them is stdin

**Comment by kyx0r** [comment]
Hmm, the fact that it prints it twice is not surprising to me. Probably can be fixed by some hack.

**Comment by OldWorldOrdr** [comment]
nope

![image](https://github.com/kyx0r/nextvi/assets/57970114/a6cc8269-5738-4b6a-9216-8a363202f9c1)

**Comment by kyx0r** [comment]
Aha, its fixed if you add files to open but not if there no files. Lemme try again

**Comment by kyx0r** [comment]
Should be fine now.

**Comment by OldWorldOrdr** [comment]
it is fixed

**Comment by kyx0r** [comment]
Keep in mind, I just updated master and filetype_shebang.patch so that patches apply smoothly.
