### ISSUE TITLE
Is gf bind in normal mode that edits the file whose address is under the cursor, a thing in Nextvi?

### ISSUE THREAD

**Issue by LaithOsama** [kyx0r/nextvi#61]
Hello,

I hope you're doing well.

First of all, I want to express my appreciation for this wonderful project and the tremendous effort you've put into it.

I'm currently torn between Neatvi and Nextvi, but I'm leaning towards Nextvi due to its HTML syntax highlighting patterns and some useful add-ons that have been integrated. However, I've encountered a real issue - the inability to edit files through links in the texts. Is this feature available but hidden, or is it simply not supported in Nextvi?

Best regards,
Leith

**Comment by LaithOsama** [comment]
What a good thing to hear!
Additionally, I would like to offer my apologies as I now realize that I may have been hasty in my initial inquiry without thoroughly reviewing the documentation you provided.

I'm currently exploring the potential of Neatvi/Nextvi as a tool for organizing my notes and texts. While I understand that replicating the full range of capabilities offered by add-ons like vimwiki is not feasible, I'm keen on making the most of this editor for this particular purpose.

Any guidance or suggestions on how to maximize the editor's utility for note-taking and wiki organization would be greatly appreciated.

Thank you once again for your assistance.

Best regards.

**Comment by LaithOsama** [comment]
Update: It turns out that the way it behaves is not suitable for my use case.
I think that Neatvi or another approach like using st's plumber patch to open files would better suit my needs.
Thank you for your assistance.

**Comment by kyx0r** [comment]
Why? 1530:vi.c you can modify it to suit your needs. If the issue is it being a macro you can modify it to either use term_exec or  call ex_edit directly. If the issue is not checking if file exists prior you can add stat() call for a check. If the issue is reading to the end of the line you can replace lbuf_get() with vi_curword().

Let me know what the current problem is and I will see if it would make sense to change its behavior.

-Kyryl

**Comment by LaithOsama** [comment]
Apologies for my delayed reply.
The issue I'm facing is related to how Nextvi handles links. Specifically, when I have a link like this:

`[Japan History](./history-of-japan.md)`
In Neatvi, it opens the file correctly. However, in Nextvi, it includes the ')' character in the filename, resulting in './history-of-japan.md)'.

I hope this clarifies the problem. Thank you for your assistance, and I appreciate your understanding regarding my delayed response.

**Comment by kyx0r** [comment]
I see now. Thank you for the follow up. That's rather a difficult problem. What if the filename actually contains )? Then Neatvi will fail. I don't like Ali's approach to solving this problem by defining some arbitrary boundary of what is a filename.

^i is designed to open files without any special processing of characters.

To solve your edge case you can make a macro to work around this specific setup.
for example:

yt):e ^p\n

Now put this into a register and set using EXINIT at startup. You could even make it more robust and automate more things.

(Additionally, you can also use vv (in normal) after failed ^i and edit the filename)

These things are documented in the readme. Let me know if you need additional assistance.
Kind Regards,
Kyryl
