### ISSUE TITLE
Remove variable length arrays

### ISSUE THREAD

**Issue by adriangrigore** [kyx0r/nextvi#66]
I was wondering if it's possible to switch from variable length arrays to normal static arrays. I'm porting nextvi to 9front, and the compiler doesn't support them.

**Comment by kyx0r** [comment]
Not efficient, but possible. replacing VLAs with malloc is fairly straightforward process.

**Comment by kyx0r** [comment]
Static arrays probably won't work, unless you be willing to make some assumptions and reserve large blocks of memory.

**Comment by adriangrigore** [comment]
So how would go about it? I can migrate to malloc, but not sure about sizes for static arrays. Migrate all VLAs to malloc-ed ones?

**Comment by adriangrigore** [comment]
Here's how nextvi looks on 9front ![nextvi on 9front](http://www.9paste.net/none/207-787-4994.png)

**Comment by kyx0r** [comment]
How did you get it to compile?

Actually, changing to static array is rather trivial. Just make 1 global char array with size of 0.5MB-1MB and reference it everywhere its needed. Basically we simulate our own stack. The only case where this would not work is multithreaded code, which does exists if you use the threaded_search.patch. Its optional however.

**Comment by adriangrigore** [comment]
> How did you get it to compile?
I just created static arrays with large sizes, but opened the issue because I was unsure about the sizes.

> Actually, changing to static array is rather trivial. Just make 1 global char array with size of 0.5MB-1MB and reference it everywhere its needed. Basically we simulate our own stack. The only case where this would not work is multithreaded code, which does exists if you use the threaded_search.patch. Its optional however.

I might switch to multi threaded code because I'm considering adding mouse support. Where can I find the threaded_search patch?

**Comment by adriangrigore** [comment]
Any other tips for porting to a multi threaded environment?

**Comment by kyx0r** [comment]
> > How did you get it to compile?
> 
> I just created static arrays with large sizes, but opened the issue because I was unsure about the sizes.

Ahh, in that case I can tell you that regex would need the most memory.

```
char nsubs[prog->sub];
```
nsubs can get quite large.


> I might switch to multi threaded code because I'm considering adding mouse support. Where can I find the threaded_search patch?

https://github.com/kyx0r/nextvi/tree/patches

Not sure if multithreading is actually required for mouse though. Because all that mouse is just reading keycodes from the terminal. Not difference from keyboard. Only question if the terminal a universal format for this.

**Comment by adriangrigore** [comment]
The terminal is not in a standard format. I doesn't support escape codes. This is  more of a GUI application than a TUI application in 9front. From what I understand, mouse support requires a multi threaded environment: https://9fans.github.io/plan9port/man/man3/thread.html.
https://wiki.9front.org/programming-gui

This what `term.c` would look like on 9front (wip) http://okturing.com/src/17118/body.

**Comment by kyx0r** [comment]
> Any other tips for porting to a multi threaded environment?

I think regex is the most problematic where just making a static array may not cut it. In that case you can add pointers in the rcode structure and malloc them at reg_comp. Then just use those pointers in re_pikevm.

**Comment by kyx0r** [comment]
Hi, any progress on this? It would be nice to add an optional patch that removes VLA for systems that may benefit from it.

**Comment by adriangrigore** [comment]
I missed you reply. Project is on hold due to job related issues. :)

**Comment by adriangrigore** [comment]
Tbh, I'd remove VLAs from the whole project!

**Comment by kyx0r** [comment]
I like VLAs, its clean and efficient. Removing them to support some compiler is fine so long as it is and opt in patch. If such patch is ready, please send it for review so it can be adopted into patches branch. 

I could implement it myself, but its not a big priority, plus I need to know that at least 1 person is using it.
