### ISSUE TITLE
visual mode equivalent?

### ISSUE THREAD

**Issue by loosefish-scapegrace** [kyx0r/nextvi#72]
hi,

one thing which i think would be useful is something similar to
vim's 'visual mode'. my idea is that a certain 'default' mark
would optionally colour-invert the space between the selection and
the mark, to make it eaiser to see where the mark is.

regardless, thanks for neatvi. it's quite nice.

**Comment by kyx0r** [comment]
Hmm, I guess I could make a patch with a new ex option that would visually highlight the positions of marks.

**Comment by kyx0r** [comment]
It's not like vim, but if your goal was to highlight the marks this patch does this:
https://github.com/kyx0r/nextvi/blob/patches/hl_mark.patch

How useful it is remains to be proven.
