### ISSUE TITLE
a way to change how big tabs are

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#76]
The default of 8 spaces is a lot, I prefer 4, some people use 2 or 3, a way to change the default would be nice.

**Comment by kyx0r** [comment]
Please see change 39 in the README:

Added ex option to change number of spaces in a tab (\t) default is set to 8.
use :se tbs=N  (N is number of spaces)

You can also edit it here: https://github.com/kyx0r/nextvi/blob/master/ex.c#L18

But I recommend using EXINIT for this.
