### ISSUE TITLE
implementing vim-like dw

### ISSUE THREAD

**Issue by loosefish-scapegrace** [kyx0r/nextvi#78]
Hi,

I've been trying to implement a patch to implement `vim`'s (inconsistent, tbf) `d/c/yw`, but I've run into trouble implementing it.
I think that the logic for this should go inside `vc_motion`, which as far as i can see is where the `dw` command is executed from. I assume that I need to replace the `o2` and `r2` variables after they are read by `vi_motion`, going back before the newline if the w enters a new line, but I wasn't able to figure out the implementation for this.

Is this the right way of doing this, or is there a better solution?

**Comment by kyx0r** [comment]
Hey, for dw command you want to edit function lbuf_wordbeg().

This is because vc_motion merely accepts the range, but the range is calculated in vi_motion.

**Comment by loosefish-scapegrace** [comment]
i finally got around to implementing this as a patch, which i sent through email (hopefully it sent correctly), so i will close this

**Comment by kyx0r** [comment]
I've received your patch. Thanks! Should be reflected on patches now.
