### ISSUE TITLE
stdin_pipe: lockup if stdin is terminal

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#81]
If you just run `vi -` the terminal locks up, ctrl+d and ctrl+c dont work, only way out I've found is closing the terminal or killing vi from another terminal

The way vim handles it is you can type anything and then press ctrl+d to open what you've typed in vim

**Comment by kyx0r** [comment]
Hello Joey,

The solution is to do a non-blocking read IO. Try last commit and see if its fixed now.

Kind Regards,
Kyryl

**Comment by OldWorldOrdr** [comment]
patch seems to not work anymore, `cat vi.c | ./vi -` opens an empty buffer

**Comment by kyx0r** [comment]
Hmm, you're right. It works in 50/50 now. I guess now there is a race condition. :/

**Comment by kyx0r** [comment]
Ok try now. The solution is to add SIGINT (^c) handler and remove it later. This way, bad pipe can be lockup can be circumvented.

**Comment by OldWorldOrdr** [comment]
fixed
