### ISSUE TITLE
arrowkeys_insert: cursor position is wrong when moving up or down a line after typing something

### ISSUE THREAD

**Issue by OldWorldOrdr** [kyx0r/nextvi#91]
if you enter insert mode on a line and type something, then go up or down a line, the cursor jumps back to the horizontal position it was in before you started typing instead of after

video showing the issue: https://asciinema.org/a/I3eR0j9paoDtfeDictWsM2kk8

**Comment by kyx0r** [comment]
I've pushed a fix for this, a bit hacky but should get the job done.

**Comment by OldWorldOrdr** [comment]
typing a bunch and pressing down moves the cursor 1 too far to the right

**Comment by OldWorldOrdr** [comment]
oh its only when I enter insert mode with 'a', doesn't happen with 'i'

**Comment by kyx0r** [comment]
I made a bunch of changes, what about now? Also dealing this end of lines and empty lines should be better.

**Comment by kyx0r** [comment]
When the cursor is over the new line character, going up and down will set it to the position of new line character on next line regardless of length. If the its on the last char it should work as expected. I think it makes sense to do that.

**Comment by OldWorldOrdr** [comment]
seems to be working great, thanks!
