### ISSUE TITLE
Edge case of missing filename

### ISSUE THREAD

**Issue by polluks** [kyx0r/nextvi#96]
```
$ vim
i
esc
ZZ
```
```
$ vi
i
esc
ZZ
write failed: cannot create file

**Comment by kyx0r** [comment]
What's wrong with that? Looks correct to me. Vim will error saying no filename.

**Comment by kyx0r** [comment]
Well, only if nothing added. Anyways I don't think vim's behavior is correct here. Its a non issue since insert mode does add \n to the line you try to edit.

**Comment by polluks** [comment]
Indeed, vim does not insert a newline.
